{ lib, ... }:
{
  terraform.required_providers = {
    incus.source = "lxc/incus";
    cloudflare.source = "cloudflare/cloudflare";
    sops.source = "carlpett/sops";
  };

  provider = {
    incus = { };

    cloudflare = {
      api_token = lib.cloudflare.api_token;
    };

    sops = { };
  };

  data.sops_file.secrets = {
    source_file = toString ./secrets.yaml;
  };

  resource.cloudflare_record.server = {
    zone_id = lib.cloudflare.zone_id;

    type = "A";
    name = "server";
    value = lib.home.ipv4;

    proxied = true;
    ttl = 1;

    comment = "generated by nix (https://github.com/thecodinglab/systems)";
  };
}
