CLOUDFLARE_API_TOKEN: ENC[AES256_GCM,data:6/nmG6kaBj1OCN1So4DmI2MIJC4E5PRhAkSedJXPMRtox1mjOSnl4g==,iv:MCpuN3B2dOllQh53ZqQCLzZCzsteoJNJt8TyCnG8p/w=,tag:LnFLTvvsykMh2LlpQ49zqg==,type:str]
CLOUDFLARE_ZONE_ID: ENC[AES256_GCM,data:9frIAfPcwU6R1Zk3DTue+fqDj0lRIvV1ZkPssLjbFyA=,iv:5xIMfXOOIA7ff4qQvKoS/nIgZshieWG8Xl+dAjOY2vo=,tag:YdlfyQQhE5WQGNqBuEKoGA==,type:str]
GITHUB_LOGIN_METHOD_ID: ENC[AES256_GCM,data:/ze89nD9CuDc8ECsErejWBb2hIjrL3il9W37F4IdEsZv1OvH,iv:U8UjWSj4DBPDR+pxc3bMqF+kopPpg6BWi9W5okGS7xE=,tag:0re8j5Q1Q0B9erlUn13N/A==,type:str]
HOME_IPV4: ENC[AES256_GCM,data:vMJDCdGtGg7hRB5cvg==,iv:dO3DNXglsXh2BfpHrlv5wbTOx1NLMCnm7HkVg/aD6aE=,tag:8drBoFUMt1L7hmUmPwCajw==,type:str]
HOME_IPV4_SUBNET: ENC[AES256_GCM,data:DeHFqdCk3Ek1ZOqrkVBbTQ==,iv:q/UpBfrnUMsJjTpLg8lv+Wa3767t1amLwG62b5ip0GQ=,tag:PkjvE6eWgFRQOfcxIOlEnQ==,type:str]
HOME_IPV6_SUBNET: ENC[AES256_GCM,data:2jqlBbOaO458zS4xEMn3cqpnAr7a41xc,iv:8LgG22mLhdAPT+Mni61GrnEO8CMULoiCvOHKqMD/EXE=,tag:j91kKtAJgctQWPW0AFTmrg==,type:str]
sops:
    age:
        - recipient: age1wgenz0mv90afzts5ay84k24yykquv4cudt208wels0v2w66j3psqwxqsk9
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBPZWtMT0dNMVBYRDYwbU5t
            SUkvb01iZjNjZXZBanJXenRZMDFvSFJrYzJjCjQ2WnZOaldOK2JxZWxPL0RBeExz
            YmFOTkhyU1YySVAzTHlqRkNHTlUvZXMKLS0tIDlCM1hZVFRraTYxMkFEMXBwT3Jw
            MlgzWVBsN1FTRytlY0QzQTF6REFmVWcKIGii8u3D2C7LJ+sdqquQRKUdH1lrqNY5
            coXcKg/Iyn6eZ6objJafpDeod7kx7VBsB4Ls5ZDIumZL1Mu0IDCv1Q==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-03-22T18:09:03Z"
    mac: ENC[AES256_GCM,data:HatgnmwjDbbWO6lVUIH5vyZJt2xSw1ktiEaqOWVwRrguBRohyT+L5ZLj1rRthHBk+c26Yc5xXiaaI6yeGb9a7V2QHxB2TeCJkkCjZOnLu79GJUvodE/VuvsGY9P1vyZNQ5A5Q47o/d5XN5uSzhrKE/nF8K/J8yqpHHZFwQGEBTU=,iv:BgKj7rzn/a2iSrYiuL7Ozq5kfjCOsQ26nqt7DjqAfVc=,tag:pMsk4IuFoSv7OkVv9l5WIQ==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.12.1
