# This file was generated by nvfetcher, please do not modify it manually.
{
  fetchgit,
  fetchurl,
  fetchFromGitHub,
  dockerTools,
}:
{
  helium = {
    pname = "helium";
    version = "0.10.8.1";
    src = fetchurl {
      url = "https://github.com/imputnet/helium-linux/releases/download/0.10.8.1/helium-0.10.8.1-x86_64.AppImage";
      sha256 = "sha256-pN/Iw1ANggDOxxFb2CN436qbcrs8/bDcEqjZC80grQs=";
    };
  };
  zen-browser = {
    pname = "zen-browser";
    version = "1.19.6b";
    src = fetchTarball {
      url = "https://github.com/zen-browser/desktop/releases/download/1.19.6b/zen.linux-x86_64.tar.xz";
      sha256 = "sha256-oBkqi6pZ61lEh1alNC25ZAssM1KKJ6chi5djkMMkhGY=";
    };
  };
}
