self:
builtins.fromJSON (builtins.readFile ../../../secrets/cloudflare.json) //
rec {
  makeDNSRecord = (name: {
    zone_id = self.cloudflare.zone_id;

    type = "CNAME";
    name = name;
    value = "server.thecodinglab.ch";

    proxied = true;
    ttl = 1;

    comment = "generated by nix (https://github.com/thecodinglab/systems)";
  });

  makeDefaultApplication = (name: {
    zone_id = self.cloudflare.zone_id;

    inherit name;
    domain = "${name}.thecodinglab.ch";
    type = "self_hosted";
  });

  makeHomeBypassAccessPolicy = ({ application_id, precedence }:
    let
      auth = {
        ip = [
          self.home.ipv4_subnet
          self.home.ipv6_subnet
        ];
      };
    in
    {
      zone_id = self.cloudflare.zone_id;
      inherit application_id;

      name = "allow home";
      decision = "bypass";
      inherit precedence;

      include = auth;
    });

  makeGithubAllowancePolicy = ({ application_id, precedence }:
    let
      auth = {
        email = [ "fw@florian-walter.ch" ];
        login_method = [ self.cloudflare.access_github_login_method_id ];
      };
    in
    {
      zone_id = self.cloudflare.zone_id;
      inherit application_id;

      name = "allow myself from everywhere";
      decision = "allow";
      inherit precedence;

      include = auth;
    }
  );
}
