#!/usr/bin/env sh

set -e

LAT=47.3769N
LON=8.5417E

MIN_BRIGHTNESS=10
MAX_BRIGHTNESS=75
INCREMENTS=1

SUNWAIT_BASE="sunwait list 1 $LAT $LON angle 2"

CURRENT=$(date +%s)
SUNRISE=$(date -d "$($SUNWAIT_BASE rise)" +%s)
SUNSET=$(date -d "$($SUNWAIT_BASE set)" +%s)

MINUTES_BEFORE_SUNRISE=$(((SUNRISE - CURRENT) / 60))
MINUTES_AFTER_SUNSET=$(((CURRENT - SUNSET) / 60))

if [ $MINUTES_BEFORE_SUNRISE -gt 0 ]; then
  BRIGHTNESS=$((MAX_BRIGHTNESS - MINUTES_BEFORE_SUNRISE * INCREMENTS))
elif [ $MINUTES_AFTER_SUNSET -gt 0 ]; then
  BRIGHTNESS=$((MAX_BRIGHTNESS - MINUTES_AFTER_SUNSET * INCREMENTS))
else
  BRIGHTNESS=$MAX_BRIGHTNESS
fi

BRIGHTNESS=$((BRIGHTNESS < MIN_BRIGHTNESS ? MIN_BRIGHTNESS : BRIGHTNESS))
BRIGHTNESS=$((BRIGHTNESS > MAX_BRIGHTNESS ? MAX_BRIGHTNESS : BRIGHTNESS))

for MONITOR in $(ddcutil detect --terse | grep I2C | sed -e 's/.*-//'); do
  ddcutil -b $MONITOR --async setvcp 10 $BRIGHTNESS &
done

wait
